// Code generated by muzak.dev/framework/tsgen. DO NOT EDIT.

/*
 * Petstore 1.2.3
 *
 * Pets, and the people they own.
 */

export interface ErrorBody {
  code: string;
  details?: ErrorDetail[];
  message: string;
  status: number;
}

export interface ErrorDetail {
  field: string;
  issue: string;
  location: string;
}

export interface ErrorResponse {
  error: ErrorBody;
  request_id?: string;
}

export interface Owner {
  email?: string;
  name: string;
}

export interface Page {
  items: Pet[];
  next?: string | null;
}

export interface Pet {
  /**
   * A Go duration such as 1500ms or 2h45m.
   */
  age: string;
  attrs: Record<string, string>;
  born: string;
  children: Pet[];
  id: string;
  kind: string;
  /**
   * What the pet answers to.
   */
  name: string;
  owner?: Owner | null;
  photo?: string;
  tags?: string[];
  weight?: number | null;
}

/**
 * The parameters of GetFilesByPath.
 *
 * GET /files/{path}
 */
export interface GetFilesByPathParams {
  path: {
    path: string;
  };
}

/**
 * The request body of GetFilesByPath.
 */
export type GetFilesByPathBody = undefined;

/**
 * What GetFilesByPath answers with when it succeeds.
 */
export type GetFilesByPathResponse = Blob;

/**
 * What GetFilesByPath answers with when it does not.
 */
export type GetFilesByPathError = ErrorResponse;

/**
 * The parameters of GetOld.
 *
 * GET /old
 */
export interface GetOldParams {
}

/**
 * The request body of GetOld.
 */
export type GetOldBody = undefined;

/**
 * What GetOld answers with when it succeeds.
 */
export type GetOldResponse = undefined;

/**
 * What GetOld answers with when it does not.
 */
export type GetOldError = ErrorResponse;

/**
 * The parameters of GetPage.
 *
 * GET /page
 */
export interface GetPageParams {
}

/**
 * The request body of GetPage.
 */
export type GetPageBody = undefined;

/**
 * What GetPage answers with when it succeeds.
 */
export type GetPageResponse = string;

/**
 * What GetPage answers with when it does not.
 */
export type GetPageError = ErrorResponse;

/**
 * The parameters of ListPets.
 *
 * List pets
 *
 * GET /pets
 */
export interface ListPetsParams {
  query: {
    cursor?: string | null;
    kind: string;
    limit?: number;
  };
}

/**
 * The request body of ListPets.
 */
export type ListPetsBody = undefined;

/**
 * What ListPets answers with when it succeeds.
 */
export type ListPetsResponse = Page;

/**
 * What ListPets answers with when it does not.
 */
export type ListPetsError = ErrorResponse;

/**
 * The parameters of PostPets.
 *
 * POST /pets
 */
export interface PostPetsParams {
  header?: {
    /**
     * The tenant the pet belongs to.
     */
    "X-Tenant"?: string;
  };
}

/**
 * The request body of PostPets.
 */
export type PostPetsBody = {
  kind?: "cat" | "dog" | "bird";
  name?: string;
  score?: 1 | 2 | 3;
  tags?: string[];
};

/**
 * What PostPets answers with when it succeeds.
 */
export type PostPetsResponse = Pet;

/**
 * What PostPets answers with when it does not.
 */
export type PostPetsError = ErrorResponse;

/**
 * The parameters of GetPetsById.
 *
 * Fetch one pet.
 * It says *\/ and <b>.
 *
 * GET /pets/{id}
 */
export interface GetPetsByIdParams {
  path: {
    id: string;
  };
  query?: {
    expand?: string[];
  };
  cookie?: {
    session?: string;
  };
}

/**
 * The request body of GetPetsById.
 */
export type GetPetsByIdBody = undefined;

/**
 * What GetPetsById answers with when it succeeds.
 */
export type GetPetsByIdResponse = Pet;

/**
 * What GetPetsById answers with when it does not.
 */
export type GetPetsByIdError = ErrorResponse;

/**
 * The parameters of DeletePetsById.
 *
 * DELETE /pets/{id}
 *
 * @deprecated
 */
export interface DeletePetsByIdParams {
  path: {
    id: string;
  };
  query?: {
    expand?: string[];
  };
  cookie?: {
    session?: string;
  };
}

/**
 * The request body of DeletePetsById.
 */
export type DeletePetsByIdBody = undefined;

/**
 * What DeletePetsById answers with when it succeeds.
 */
export type DeletePetsByIdResponse = undefined;

/**
 * What DeletePetsById answers with when it does not.
 */
export type DeletePetsByIdError = ErrorResponse;

/**
 * The parameters of GetPetsByIdPhoto.
 *
 * GET /pets/{id}/photo
 */
export interface GetPetsByIdPhotoParams {
  path: {
    id: string;
  };
  query?: {
    expand?: string[];
  };
  cookie?: {
    session?: string;
  };
}

/**
 * The request body of GetPetsByIdPhoto.
 */
export type GetPetsByIdPhotoBody = undefined;

/**
 * What GetPetsByIdPhoto answers with when it succeeds.
 */
export type GetPetsByIdPhotoResponse = Blob;

/**
 * What GetPetsByIdPhoto answers with when it does not.
 */
export type GetPetsByIdPhotoError = ErrorResponse;

/**
 * The parameters of PutPetsByIdPhoto.
 *
 * PUT /pets/{id}/photo
 */
export interface PutPetsByIdPhotoParams {
  path: {
    id: string;
  };
}

/**
 * The request body of PutPetsByIdPhoto.
 */
export type PutPetsByIdPhotoBody = {
  caption?: string;
  photo: Blob;
};

/**
 * What PutPetsByIdPhoto answers with when it succeeds.
 */
export type PutPetsByIdPhotoResponse = undefined;

/**
 * What PutPetsByIdPhoto answers with when it does not.
 */
export type PutPetsByIdPhotoError = ErrorResponse;

/**
 * The parameters of GetPing.
 *
 * GET /ping
 */
export interface GetPingParams {
}

/**
 * The request body of GetPing.
 */
export type GetPingBody = undefined;

/**
 * What GetPing answers with when it succeeds.
 */
export type GetPingResponse = Record<string, boolean>;

/**
 * What GetPing answers with when it does not.
 */
export type GetPingError = ErrorResponse;

/**
 * Every operation of the API, by the name its types are written under.
 */
export interface Operations {
  GetFilesByPath: {
    method: "GET";
    path: "/files/{path}";
    params: GetFilesByPathParams;
    body: GetFilesByPathBody;
    response: GetFilesByPathResponse;
    error: GetFilesByPathError;
  };
  GetOld: {
    method: "GET";
    path: "/old";
    params: GetOldParams;
    body: GetOldBody;
    response: GetOldResponse;
    error: GetOldError;
  };
  GetPage: {
    method: "GET";
    path: "/page";
    params: GetPageParams;
    body: GetPageBody;
    response: GetPageResponse;
    error: GetPageError;
  };
  ListPets: {
    method: "GET";
    path: "/pets";
    params: ListPetsParams;
    body: ListPetsBody;
    response: ListPetsResponse;
    error: ListPetsError;
  };
  PostPets: {
    method: "POST";
    path: "/pets";
    params: PostPetsParams;
    body: PostPetsBody;
    response: PostPetsResponse;
    error: PostPetsError;
  };
  GetPetsById: {
    method: "GET";
    path: "/pets/{id}";
    params: GetPetsByIdParams;
    body: GetPetsByIdBody;
    response: GetPetsByIdResponse;
    error: GetPetsByIdError;
  };
  DeletePetsById: {
    method: "DELETE";
    path: "/pets/{id}";
    params: DeletePetsByIdParams;
    body: DeletePetsByIdBody;
    response: DeletePetsByIdResponse;
    error: DeletePetsByIdError;
  };
  GetPetsByIdPhoto: {
    method: "GET";
    path: "/pets/{id}/photo";
    params: GetPetsByIdPhotoParams;
    body: GetPetsByIdPhotoBody;
    response: GetPetsByIdPhotoResponse;
    error: GetPetsByIdPhotoError;
  };
  PutPetsByIdPhoto: {
    method: "PUT";
    path: "/pets/{id}/photo";
    params: PutPetsByIdPhotoParams;
    body: PutPetsByIdPhotoBody;
    response: PutPetsByIdPhotoResponse;
    error: PutPetsByIdPhotoError;
  };
  GetPing: {
    method: "GET";
    path: "/ping";
    params: GetPingParams;
    body: GetPingBody;
    response: GetPingResponse;
    error: GetPingError;
  };
}
