// Code generated by muzak.dev/framework/tsgen. DO NOT EDIT.

/*
 * Petstore 1.2.3
 *
 * Pets, and the people they own.
 */

export interface ErrorBody {
  code: string;
  details?: ErrorDetail[];
  message: string;
  status: number;
}

export interface ErrorDetail {
  field: string;
  issue: string;
  location: string;
}

export interface ErrorResponse {
  error: ErrorBody;
  request_id?: string;
}

export interface Owner {
  email?: string;
  name: string;
}

export interface Page {
  items: Pet[];
  next?: string | null;
}

export interface Pet {
  /**
   * A Go duration such as 1500ms or 2h45m.
   */
  age: string;
  attrs: Record<string, string>;
  born: string;
  children: Pet[];
  id: string;
  kind: string;
  /**
   * What the pet answers to.
   */
  name: string;
  owner?: Owner | null;
  photo?: string;
  tags?: string[];
  weight?: number | null;
}

/**
 * The parameters of GetFilesByPath.
 *
 * GET /files/{path}
 */
export interface GetFilesByPathParams {
  path: {
    path: string;
  };
}

/**
 * The request body of GetFilesByPath.
 */
export type GetFilesByPathBody = undefined;

/**
 * What GetFilesByPath answers with when it succeeds.
 */
export type GetFilesByPathResponse = Blob;

/**
 * What GetFilesByPath answers with when it does not.
 */
export type GetFilesByPathError = ErrorResponse;

/**
 * The parameters of GetOld.
 *
 * GET /old
 */
export interface GetOldParams {
}

/**
 * The request body of GetOld.
 */
export type GetOldBody = undefined;

/**
 * What GetOld answers with when it succeeds.
 */
export type GetOldResponse = undefined;

/**
 * What GetOld answers with when it does not.
 */
export type GetOldError = ErrorResponse;

/**
 * The parameters of GetPage.
 *
 * GET /page
 */
export interface GetPageParams {
}

/**
 * The request body of GetPage.
 */
export type GetPageBody = undefined;

/**
 * What GetPage answers with when it succeeds.
 */
export type GetPageResponse = string;

/**
 * What GetPage answers with when it does not.
 */
export type GetPageError = ErrorResponse;

/**
 * The parameters of ListPets.
 *
 * List pets
 *
 * GET /pets
 */
export interface ListPetsParams {
  query: {
    cursor?: string | null;
    kind: string;
    limit?: number;
  };
}

/**
 * The request body of ListPets.
 */
export type ListPetsBody = undefined;

/**
 * What ListPets answers with when it succeeds.
 */
export type ListPetsResponse = Page;

/**
 * What ListPets answers with when it does not.
 */
export type ListPetsError = ErrorResponse;

/**
 * The parameters of PostPets.
 *
 * POST /pets
 */
export interface PostPetsParams {
  header?: {
    /**
     * The tenant the pet belongs to.
     */
    "X-Tenant"?: string;
  };
}

/**
 * The request body of PostPets.
 */
export type PostPetsBody = {
  kind?: "cat" | "dog" | "bird";
  name?: string;
  score?: 1 | 2 | 3;
  tags?: string[];
};

/**
 * What PostPets answers with when it succeeds.
 */
export type PostPetsResponse = Pet;

/**
 * What PostPets answers with when it does not.
 */
export type PostPetsError = ErrorResponse;

/**
 * The parameters of GetPetsById.
 *
 * Fetch one pet.
 * It says *\/ and <b>.
 *
 * GET /pets/{id}
 */
export interface GetPetsByIdParams {
  path: {
    id: string;
  };
  query?: {
    expand?: string[];
  };
  cookie?: {
    session?: string;
  };
}

/**
 * The request body of GetPetsById.
 */
export type GetPetsByIdBody = undefined;

/**
 * What GetPetsById answers with when it succeeds.
 */
export type GetPetsByIdResponse = Pet;

/**
 * What GetPetsById answers with when it does not.
 */
export type GetPetsByIdError = ErrorResponse;

/**
 * The parameters of DeletePetsById.
 *
 * DELETE /pets/{id}
 *
 * @deprecated
 */
export interface DeletePetsByIdParams {
  path: {
    id: string;
  };
  query?: {
    expand?: string[];
  };
  cookie?: {
    session?: string;
  };
}

/**
 * The request body of DeletePetsById.
 */
export type DeletePetsByIdBody = undefined;

/**
 * What DeletePetsById answers with when it succeeds.
 */
export type DeletePetsByIdResponse = undefined;

/**
 * What DeletePetsById answers with when it does not.
 */
export type DeletePetsByIdError = ErrorResponse;

/**
 * The parameters of GetPetsByIdPhoto.
 *
 * GET /pets/{id}/photo
 */
export interface GetPetsByIdPhotoParams {
  path: {
    id: string;
  };
  query?: {
    expand?: string[];
  };
  cookie?: {
    session?: string;
  };
}

/**
 * The request body of GetPetsByIdPhoto.
 */
export type GetPetsByIdPhotoBody = undefined;

/**
 * What GetPetsByIdPhoto answers with when it succeeds.
 */
export type GetPetsByIdPhotoResponse = Blob;

/**
 * What GetPetsByIdPhoto answers with when it does not.
 */
export type GetPetsByIdPhotoError = ErrorResponse;

/**
 * The parameters of PutPetsByIdPhoto.
 *
 * PUT /pets/{id}/photo
 */
export interface PutPetsByIdPhotoParams {
  path: {
    id: string;
  };
}

/**
 * The request body of PutPetsByIdPhoto.
 */
export type PutPetsByIdPhotoBody = {
  caption?: string;
  photo: Blob;
};

/**
 * What PutPetsByIdPhoto answers with when it succeeds.
 */
export type PutPetsByIdPhotoResponse = undefined;

/**
 * What PutPetsByIdPhoto answers with when it does not.
 */
export type PutPetsByIdPhotoError = ErrorResponse;

/**
 * The parameters of GetPing.
 *
 * GET /ping
 */
export interface GetPingParams {
}

/**
 * The request body of GetPing.
 */
export type GetPingBody = undefined;

/**
 * What GetPing answers with when it succeeds.
 */
export type GetPingResponse = Record<string, boolean>;

/**
 * What GetPing answers with when it does not.
 */
export type GetPingError = ErrorResponse;

/**
 * Every operation of the API, by the name its types are written under.
 */
export interface Operations {
  GetFilesByPath: {
    method: "GET";
    path: "/files/{path}";
    params: GetFilesByPathParams;
    body: GetFilesByPathBody;
    response: GetFilesByPathResponse;
    error: GetFilesByPathError;
  };
  GetOld: {
    method: "GET";
    path: "/old";
    params: GetOldParams;
    body: GetOldBody;
    response: GetOldResponse;
    error: GetOldError;
  };
  GetPage: {
    method: "GET";
    path: "/page";
    params: GetPageParams;
    body: GetPageBody;
    response: GetPageResponse;
    error: GetPageError;
  };
  ListPets: {
    method: "GET";
    path: "/pets";
    params: ListPetsParams;
    body: ListPetsBody;
    response: ListPetsResponse;
    error: ListPetsError;
  };
  PostPets: {
    method: "POST";
    path: "/pets";
    params: PostPetsParams;
    body: PostPetsBody;
    response: PostPetsResponse;
    error: PostPetsError;
  };
  GetPetsById: {
    method: "GET";
    path: "/pets/{id}";
    params: GetPetsByIdParams;
    body: GetPetsByIdBody;
    response: GetPetsByIdResponse;
    error: GetPetsByIdError;
  };
  DeletePetsById: {
    method: "DELETE";
    path: "/pets/{id}";
    params: DeletePetsByIdParams;
    body: DeletePetsByIdBody;
    response: DeletePetsByIdResponse;
    error: DeletePetsByIdError;
  };
  GetPetsByIdPhoto: {
    method: "GET";
    path: "/pets/{id}/photo";
    params: GetPetsByIdPhotoParams;
    body: GetPetsByIdPhotoBody;
    response: GetPetsByIdPhotoResponse;
    error: GetPetsByIdPhotoError;
  };
  PutPetsByIdPhoto: {
    method: "PUT";
    path: "/pets/{id}/photo";
    params: PutPetsByIdPhotoParams;
    body: PutPetsByIdPhotoBody;
    response: PutPetsByIdPhotoResponse;
    error: PutPetsByIdPhotoError;
  };
  GetPing: {
    method: "GET";
    path: "/ping";
    params: GetPingParams;
    body: GetPingBody;
    response: GetPingResponse;
    error: GetPingError;
  };
}

/** How createClient reaches the API. */
export interface ClientOptions {
  /** The root the API is served under, such as "https://api.example.com/v1". */
  baseUrl: string;
  /** The fetch requests are sent with, the global one when it is left out. */
  fetch?: typeof fetch;
  /** Headers sent with every request, such as an Authorization. */
  headers?: Record<string, string>;
}

/** A response whose status is not a success, with its body read. */
export class ApiError extends Error {
  /** The status the API answered with. */
  readonly status: number;
  /** The body, parsed when it is JSON and as text otherwise. */
  readonly body: unknown;

  constructor(status: number, body: unknown) {
    super("the API answered with status " + status);
    this.name = "ApiError";
    this.status = status;
    this.body = body;
  }
}

type Fields = Record<string, unknown> | undefined;

interface Sent {
  path?: Fields;
  query?: Fields;
  header?: Fields;
  cookie?: Fields;
}

function eachValue(fields: Fields, add: (name: string, value: string) => void): void {
  if (fields === undefined) {
    return;
  }
  for (const name of Object.keys(fields)) {
    const value: unknown = fields[name];
    const values: unknown[] = Array.isArray(value) ? value : [value];
    for (const item of values) {
      if (item !== undefined && item !== null) {
        add(name, String(item));
      }
    }
  }
}

function encodeBody(kind: string, body: unknown, headers: Headers): BodyInit | undefined {
  if (body === undefined || kind === "none") {
    return undefined;
  }
  if (kind === "json") {
    headers.set("Content-Type", "application/json");
    return JSON.stringify(body);
  }
  if (kind === "blob") {
    return body as Blob;
  }
  const fields = body as Record<string, unknown>;
  if (kind === "urlencoded") {
    const encoded = new URLSearchParams();
    eachValue(fields, (name, value) => encoded.append(name, value));
    return encoded;
  }
  const form = new FormData();
  for (const name of Object.keys(fields)) {
    const value: unknown = fields[name];
    const values: unknown[] = Array.isArray(value) ? value : [value];
    for (const item of values) {
      if (item instanceof Blob) {
        form.append(name, item, name);
      } else if (item !== undefined && item !== null) {
        form.append(name, String(item));
      }
    }
  }
  return form;
}

async function decode(response: Response, kind: string): Promise<unknown> {
  if (kind === "none" || response.status === 204 || response.status === 205) {
    return undefined;
  }
  if (kind === "blob") {
    return response.blob();
  }
  const text = await response.text();
  if (kind === "text") {
    return text;
  }
  return text === "" ? undefined : JSON.parse(text);
}

async function send(
  options: ClientOptions,
  method: string,
  path: string,
  sent: Sent,
  bodyKind: string,
  body: unknown,
  responseKind: string,
  init: RequestInit | undefined,
): Promise<unknown> {
  let base = options.baseUrl;
  while (base.endsWith("/")) {
    base = base.slice(0, -1);
  }
  const url = new URL(base + path);
  eachValue(sent.query, (name, value) => url.searchParams.append(name, value));
  const headers = new Headers(options.headers);
  eachValue(sent.header, (name, value) => headers.append(name, value));
  if (responseKind === "json" && !headers.has("Accept")) {
    headers.set("Accept", "application/json");
  }
  const encoded = encodeBody(bodyKind, body, headers);
  const doFetch = options.fetch ?? fetch;
  const response = await doFetch(url, { ...init, method, headers, body: encoded });
  if (!response.ok) {
    const text = await response.text();
    let parsed: unknown = text;
    try {
      parsed = JSON.parse(text);
    } catch {
      // Not JSON: the text is kept as it is.
    }
    throw new ApiError(response.status, parsed);
  }
  return decode(response, responseKind);
}

function pathSegment(name: string, value: unknown): string {
  const text = value === undefined || value === null ? "" : String(value);
  if (text === "" || text === "." || text === ".." || text.includes("/")) {
    throw new TypeError("the path parameter " + name + " is empty, a dot segment or holds a /, which would name another route");
  }
  return encodeURIComponent(text);
}

/**
 * Creates a client for the API, with one method per operation.
 */
export function createClient(options: ClientOptions) {
  return {
    getFilesByPath(params: GetFilesByPathParams, init?: RequestInit): Promise<GetFilesByPathResponse> {
      return send(options, "GET", "/files/" + pathSegment("path", params.path["path"]), params, "none", undefined, "blob", init) as Promise<GetFilesByPathResponse>;
    },
    getOld(params?: GetOldParams, init?: RequestInit): Promise<GetOldResponse> {
      return send(options, "GET", "/old", params ?? {}, "none", undefined, "none", init) as Promise<GetOldResponse>;
    },
    getPage(params?: GetPageParams, init?: RequestInit): Promise<GetPageResponse> {
      return send(options, "GET", "/page", params ?? {}, "none", undefined, "text", init) as Promise<GetPageResponse>;
    },
    /**
     * List pets
     */
    listPets(params: ListPetsParams, init?: RequestInit): Promise<ListPetsResponse> {
      return send(options, "GET", "/pets", params, "none", undefined, "json", init) as Promise<ListPetsResponse>;
    },
    postPets(params: PostPetsParams, body: PostPetsBody, init?: RequestInit): Promise<PostPetsResponse> {
      return send(options, "POST", "/pets", params, "json", body, "json", init) as Promise<PostPetsResponse>;
    },
    /**
     * Fetch one pet.
     * It says *\/ and <b>.
     */
    getPetsById(params: GetPetsByIdParams, init?: RequestInit): Promise<GetPetsByIdResponse> {
      return send(options, "GET", "/pets/" + pathSegment("id", params.path["id"]), params, "none", undefined, "json", init) as Promise<GetPetsByIdResponse>;
    },
    /**
     * @deprecated
     */
    deletePetsById(params: DeletePetsByIdParams, init?: RequestInit): Promise<DeletePetsByIdResponse> {
      return send(options, "DELETE", "/pets/" + pathSegment("id", params.path["id"]), params, "none", undefined, "none", init) as Promise<DeletePetsByIdResponse>;
    },
    getPetsByIdPhoto(params: GetPetsByIdPhotoParams, init?: RequestInit): Promise<GetPetsByIdPhotoResponse> {
      return send(options, "GET", "/pets/" + pathSegment("id", params.path["id"]) + "/photo", params, "none", undefined, "blob", init) as Promise<GetPetsByIdPhotoResponse>;
    },
    putPetsByIdPhoto(params: PutPetsByIdPhotoParams, body: PutPetsByIdPhotoBody, init?: RequestInit): Promise<PutPetsByIdPhotoResponse> {
      return send(options, "PUT", "/pets/" + pathSegment("id", params.path["id"]) + "/photo", params, "form", body, "none", init) as Promise<PutPetsByIdPhotoResponse>;
    },
    getPing(params?: GetPingParams, init?: RequestInit): Promise<GetPingResponse> {
      return send(options, "GET", "/ping", params ?? {}, "none", undefined, "json", init) as Promise<GetPingResponse>;
    },
  };
}
